# PRACTICE SESSION -1


- AIM :-
    - TO IMPORT THE FOLLOWING DATA AND CREATE DATA FRAME FORM THE IMPORTED DATA

# DATAS TO BE IMPOTED

  1. CSV FILE
  2. XML FILE
  3. EXCEL FILE
  4. HTML FILE
  5. WEB PAGE

# 1.1 Importing from the csv file (House Price Prediction Dataset.csv) and getting the basic info of the data set

In [8]:
# importing pandas library to import data

import pandas as pd

df = pd.read_csv("House Price Prediction Dataset.csv")

print(df)

        Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Location  Condition  \
0        1  1360         5          4       3       1970  Downtown  Excellent
1        2  4272         5          4       3       1958  Downtown  Excellent
2        3  3592         2          2       3       1938  Downtown       Good
3        4   966         4          2       2       1902  Suburban       Fair
4        5  4926         1          4       2       1975  Downtown       Fair
...    ...   ...       ...        ...     ...        ...       ...        ...
1995  1996  4994         5          4       3       1923  Suburban       Poor
1996  1997  3046         5          2       1       2019  Suburban       Poor
1997  1998  1062         5          1       2       1903     Rural       Poor
1998  1999  4062         3          1       2       1936     Urban  Excellent
1999  2000  2989         5          1       3       1903  Suburban       Fair

     Garage   Price
0        No  149919
1        No  424998
2        No  266746
3       Yes  244020
4       Yes  636056
...     ...     ...
1995     No  295620
1996    Yes  580929
1997     No  476925
1998    Yes  161119
1999     No  482525

[2000 rows x 10 columns]

In [9]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [18]:
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 156.4 KB

Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='str')

# 1.2 exporting the selected datas to the EXCEL FILE as (houseprice.xlsx)

In [16]:
selected  = df[["Bedrooms","Price"]]

selected.to_excel("bedroomtoaera price.xlsx", index=False)

df.to_excel("houseprice.xlsx", index=False)

# 2.1 Importing the excel file (houseprice.xlsx) via pandas and getting the basic info of the data set

In [21]:
df1 = pd.read_excel("houseprice.xlsx" , sheet_name="Sheet1")

print(df1)

        Id  Area  Bedrooms  Bathrooms  Floors  YearBuilt  Location  Condition  \
0        1  1360         5          4       3       1970  Downtown  Excellent
1        2  4272         5          4       3       1958  Downtown  Excellent
2        3  3592         2          2       3       1938  Downtown       Good
3        4   966         4          2       2       1902  Suburban       Fair
4        5  4926         1          4       2       1975  Downtown       Fair
...    ...   ...       ...        ...     ...        ...       ...        ...
1995  1996  4994         5          4       3       1923  Suburban       Poor
1996  1997  3046         5          2       1       2019  Suburban       Poor
1997  1998  1062         5          1       2       1903     Rural       Poor
1998  1999  4062         3          1       2       1936     Urban  Excellent
1999  2000  2989         5          1       3       1903  Suburban       Fair

     Garage   Price
0        No  149919
1        No  424998
2        No  266746
3       Yes  244020
4       Yes  636056
...     ...     ...
1995     No  295620
1996    Yes  580929
1997     No  476925
1998    Yes  161119
1999     No  482525

[2000 rows x 10 columns]

In [22]:
df1.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [23]:
df1.info()
df1.columns

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 156.4 KB

Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='str')

# 3.1 Importing a Xml file and getting the basic info of the xml file

In [26]:
df2 = pd.read_xml("https://www.w3schools.com/xml/cd_catalog.xml")

print(df2)

                       TITLE             ARTIST COUNTRY         COMPANY  \
0           Empire Burlesque          Bob Dylan     USA        Columbia
1            Hide your heart       Bonnie Tyler      UK     CBS Records
2              Greatest Hits       Dolly Parton     USA             RCA
3        Still got the blues         Gary Moore      UK  Virgin records
4                       Eros    Eros Ramazzotti      EU             BMG
5             One night only           Bee Gees      UK         Polydor
6             Sylvias Mother            Dr.Hook      UK             CBS
7                 Maggie May        Rod Stewart      UK        Pickwick
8                    Romanza     Andrea Bocelli      EU         Polydor
9   When a man loves a woman       Percy Sledge     USA        Atlantic
10               Black angel        Savage Rose      EU            Mega
11      1999 Grammy Nominees               Many     USA          Grammy
12        For the good times       Kenny Rogers      UK    Mucik Master
13          Big Willie style         Will Smith     USA        Columbia
14              Tupelo Honey       Van Morrison      UK         Polydor
15                Soulsville          Jorn Hoel  Norway             WEA
16          The very best of        Cat Stevens      UK          Island
17                      Stop          Sam Brown      UK         A and M
18           Bridge of Spies              T'Pau      UK           Siren
19            Private Dancer        Tina Turner      UK         Capitol
20            Midt om natten         Kim Larsen      EU          Medley
21    Pavarotti Gala Concert  Luciano Pavarotti      UK           DECCA
22       The dock of the bay       Otis Redding     USA    Stax Records
23              Picture book         Simply Red      EU         Elektra
24                       Red     The Communards      UK          London
25          Unchain my heart         Joe Cocker     USA             EMI

    PRICE  YEAR
0    10.9  1985
1     9.9  1988
2     9.9  1982
3    10.2  1990
4     9.9  1997
5    10.9  1998
6     8.1  1973
7     8.5  1990
8    10.8  1996
9     8.7  1987
10   10.9  1995
11   10.2  1999
12    8.7  1995
13    9.9  1997
14    8.2  1971
15    7.9  1996
16    8.9  1990
17    8.9  1988
18    7.9  1987
19    8.9  1983
20    7.8  1983
21    9.9  1991
22    7.9  1968
23    7.2  1985
24    7.8  1987
25    8.2  1987

In [27]:
df2.head()

                 TITLE           ARTIST COUNTRY         COMPANY  PRICE  YEAR
0     Empire Burlesque        Bob Dylan     USA        Columbia   10.9  1985
1      Hide your heart     Bonnie Tyler      UK     CBS Records    9.9  1988
2        Greatest Hits     Dolly Parton     USA             RCA    9.9  1982
3  Still got the blues       Gary Moore      UK  Virgin records   10.2  1990
4                 Eros  Eros Ramazzotti      EU             BMG    9.9  1997

# 3.2 Exporting the xml file to excel file named as (cdcatlog.xlsx)

In [28]:
df2.to_excel("cd_catalog.xlsx", index=False)

# 4.1 Importing WEB file and getting datas from it

In [31]:
url = "https://www.worldometers.info/world-population/population-by-country/"

tables = pd.read_html(url)

print(len(tables))

HTTPError: HTTP Error 403: Forbidden

# 5.1 Importing the HTML File and getting the basic info

In [34]:
df3 = pd.read_html("sample.html")

print(df3)

[  House ID  Area  Bedrooms  Bathrooms  Floors  Parking    Location     Price
0     H101  1200         2          2       1        1     Chennai   4500000
1     H102  1500         3          2       2        1   Bangalore   6200000
2     H103  1800         3          3       2        2   Hyderabad   7900000
3     H104  2200         4          3       2        2      Mumbai  12000000
4     H105  2800         5          4       3        3       Delhi  18000000
5     H106  1600         3          2       2        1  Coimbatore   5800000
6     H107  1350         2          2       1        1     Madurai   4100000
7     H108  3000         5          5       3        3     Chennai  21000000]

In [35]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [36]:
df.info()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   str
 7   Condition  2000 non-null   str
 8   Garage     2000 non-null   str
 9   Price      2000 non-null   int64
dtypes: int64(7), str(3)
memory usage: 156.4 KB

Index(['Id', 'Area', 'Bedrooms', 'Bathrooms', 'Floors', 'YearBuilt',
       'Location', 'Condition', 'Garage', 'Price'],
      dtype='str')